version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: eldamoapi
    binary: eldamoapi
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
